[metadata]
  name = "Shelman Theme" # Shelman Dark
  origin_url = ""

[colors]
  ansi = [
    "#000000",
    "#ff0035",
    "#85ff00",
    "#ffc900",
    "#00a7ff",
    "#cb01ff",
    "#00e0ff",
    "#f0f0f0"
  ]

  brights = [
    "#000000",
    "#ffb4af",
    "#d2ffba",
    "#ffebb7",
    "#b1deff",
    "#edb5ff",
    "#bdf4ff",
    "#ffffff"
  ]

  background = "#11171d"
  foreground = "#e3e0cd"
  cursor_bg = "#b3ff58"
  cursor_fg = "#000000"
  cursor_border = "#000000"
  selection_bg = "#d7d7d7"
  selection_fg = "#000000"
