# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: in_memory_sqlite3
    driver: sqlite3
    dataSourceName: ':memory:'
  - alias: postgres_local
    driver: postgresql
    dataSourceName: 'host=localhost port=5433 user=test password=test dbname=test'
