version: 2
root-markers:
- .git/

tools:
  clang-format: &clang-format
    format-command: 'clang-format -style="{BasedOnStyle: Google, IndentWidth: 2, AlignConsecutiveDeclarations: true, AlignConsecutiveAssignments: true, ColumnLimit: 0}"'
    format-stdin: true

languages:
  proto:
    - <<: *clang-format
