add_newline = false

format = """
$status\
$cmd_duration\
$jobs\
$kubernetes\
"""
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# """

# $shlvl\
# $directory\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $dart\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $ruby\
# $rust\
# $swift\
# $terraform\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $env_var\
# $crystal\
# $cmd_duration\
# $custom\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# """

[hostname]
ssh_only = false
format = '#\[bg=red\] $hostname '
style = ""

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
truncate_to_repo = false
style = "bold"

[git_branch]
format = '#\[fg=#212121]\▕#\[bg=green,fg=#f7f7f7\] $symbol$branch '
style = ""

[git_commit]
format = '$hash'
style = ""

[git_state]
format = "$state( $progress_current/$progress_total)"
style = ""

[git_status]
style = ""

[kubernetes]
disabled = false
format = '#\[fg=#212121\]▕#\[bg=#0D47A1,fg=#80DEEA\] $symbol$context(\($namespace\)) '
style = ""

[time]
disabled = false
style = ""

[golang]
format = '#\[fg=#212121\]▕#\[bg=#00ACC1,fg=#f7f7f7\] $symbol$version '
style = ""

[jobs]
format = '#\[fg=#212121\]▕#\[bg=#7E57C2,fg=#f7f7f7\] $symbol$number '
style = ""
disabled = false

[status]
format = '\#\[fg=#212121\]▕#[bg=red,fg=#f7f7f7\] $symbol$status '
style = ""
disabled = false

[cmd_duration]
format = '#\[fg=#212121\]▕#\[bg=#558B2F,fg=#f7f7f7\] ⏳$duration '
style = ""
