[user]
name = "Lars Sjöström"
email = "lars@radicore.se"

[aliases]
d = ["diff", "--tool=difftu"]
dd = ["diff", "--git"]
ds = ["diff", "--tool=difft"]
l = ["log", "--limit=25", "-T", "builtin_log_comfortable", "-r", "(main..@) | (main..@)-"]
la = ["log", "--limit=25", "-T", "builtin_log_oneline", "-r", "all()"]
s = ["show", "--tool=difftu"]
ss = ["show", "--tool=difft"]

[ui]
default-command = [ "log", "--limit=25", "-T", "builtin_log_comfortable" ]
pager = "delta"

[colors]
[colors."commit_id prefix"]
bold = true

[colors."diff added token"]
underline = false

[colors.rest]
bold = false

[git]
push-bookmark-prefix = "lsjostro/push-"

[merge-tools]
[merge-tools.difft]
diff-args = ["--color=always", "--missing-as-empty", "$left", "$right"]

[merge-tools.difftu]
diff-args = ["--color=always", "--display=inline", "--missing-as-empty", "$left", "$right"]
program = "difft"

[revset-aliases]
open = "(mine() ~ ::trunk()) ~ heads(empty())"
ready = "open() ~ (wip::)"
"trunk()" = "latest((present(main) | present(master)) & remote_bookmarks())"
"user(x)" = "author(x) | committer(x)"
wip = "description(\"wip: \")"

[signing]
backend = "ssh"
key = "/home/lsjostrom/.ssh/git_signing_key.pub"
sign-all = true

[signing.backends.ssh]
allowed-signers = "/home/lsjostrom/.ssh/authorized_keys"
